version: '3'

services:
  signaling-server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - CORS_ORIGIN=*
    restart: unless-stopped 